### PR TITLE
17 - Task Card - Display Title

### LINKED ISSUE #17: [FEATURE] Task card - Display task title
## 🚀 Feature

The task card should display the title of the task.

### Motivation

User organization.

### LINKED ISSUE #42: [BUG] Empty task card
## 🐛 Bug Report

Task cards can be created with no title. They shouldn't.

### Steps to Reproduce

Click the add task button.

#### Screenshot

That thin line shown between the input box and the correct task card with text is an empty task card.

Image

### Expected Behavior

When trying to create a task with no title input, it should do nothing.  A viable solution would be to this bug is to disable the button "Add" when no text is written in the input.

### PR DESCRIPTION
**Pull request by levdevs**
## Motivation

Closes #17 
Every task added through the input field now becomes a visually distinct element on a vertical list display.

## Summary of changes
- Added the TaskCard component, which holds the title of the task. Styles provided by Bootstrap.
- Fixes #42, featuring additional logic when handling task creation.
- Miscellaneous variable name replacements.

## Checklist
- [x] Tested the changes locally.
- [x] Reviewed the changes on GitHub, line by line.

### CODE REVIEW

File: src/components/taskCreator.js [hunk 1]
```diff
@@ -28,8 +30,8 @@ export default function TaskCreator({ createTask }) {
                 onChange={(e) => setTaskTitle(e.target.value)}
                 value={taskTitle} />
 
-            <button class="btn btn-secondary btn-add" id="add-task">
-                <span class="material-symbols-outlined" id="inputGroup-sizing-default">
+            <button className="btn btn-secondary btn-add" id="add-task">
```
Comment (joac001) [inline src/components/taskCreator.js:33]: I would add in the button tag for this other tag:
```shell
<button className="btn btn-secondary btn-add" id="add-task" disabled={taskTitle.trim().length == 0}>
```
So it just disables the button when there's no input. It's more compelling, and it helps the user experience.

Comment (levdevs) [reply src/components/taskCreator.js]: Agreed, submitted the appropriate changes

**Review by joac001 — APPROVED** [review]
Everything is good
